### ISSUE TITLE
feature request "GetDescriptionString"

### ISSUE THREAD

**Issue by Rolf-M** [bobaoskit/bobaos.pub#1]
Hi,
from what I read in the weinzierl documentation, there is also the chance to get the description text (I would assume the text written in ETS for the datapoint). If this is the one, it would be cool to have this in the "getDescription" response json. It would make the human readability more easy.
Regards, Rolf

**Comment by shabunin** [comment]
Hi, Rolf

I believe this is implemented in this fork of core module: https://github.com/haidarcheaitogt/bobaos

I was implementing description string feature at first, but caught some error and thought that kBerry doesn't support it. Mayhaps I just got no string configured, mayhaps it was not supported yet back in 2017, who knows. Will try soon. Kind of cool function - some typical configurations may be done through ETS only.

**Comment by shabunin** [comment]
Added method into 2.0.13 version. Still, get error #5 - service not supported.
According to https://www.weinzierl.de/images/download/development/830/KnxBAOS_Users_Guide.pdf, pages 42 and 85 it is not implemented in BAOS 83x modules.
