### ISSUE TITLE
feature request "putValue" without writing to bus

### ISSUE THREAD

**Issue by Rolf-M** [bobaoskit/bobaos.pub#2]
Hi,
it would be cool to have a "putValue" (or other name) instruction, to write a Baos Datapoint, without writing it to the bus. This should be possible with the BAOS 838. My use case is, that I have a script sending the time to the bus. At the Moment I do this every 10 Minutes, since it might happen that a bus device is rebooted and then it will show the wrong time. If I could update the time, without sending telegrams a rebooted device will always read the correct time.
Thanks and regards, Rolf

**Comment by shabunin** [comment]
Check 2.0.13 version of bobaos core module, bobaos.pub and bobaos.sub.
There is no command in bobaos-tool yet. 
I didn't implement this feature before because couldn't find decent name for method. Thanks =)

**Comment by shabunin** [comment]
Check 2.0.13 version of bobaos core module, bobaos.pub and bobaos.sub.
There is no command in bobaos-tool yet. 
I didn't implement this feature before because couldn't find decent name for method. Thanks =)

**Comment by Rolf-M** [comment]
So cool, thank you! I'll try it right away
