### ISSUE TITLE
hello i got this issue ...

### ISSUE THREAD

**Issue by cougalix** [bobaoskit/bobaos.pub#3]
sorry but i am lost ;-)

  ()--()     hello, friend
    \"/_     here comes bobaos
     '  )    learn and enjoy
       ~

2020-03-05 16:31:53 [UTC]
Starting bobaos.pub.
Error  with bobaos core module Error Resource temporarily unavailable Cannot loc                                                                             k port.
(node:1913) UnhandledPromiseRejectionWarning: Error: Error Resource temporarily                                                                              unavailable Cannot lock port
(node:1913) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                                              error originated either by throwing inside of an async function without a catch                                                                              block, or by rejecting a promise which was not handled with .catch(). To termina                                                                             te the node process on unhandled promise rejection, use the CLI flag `--unhandle                                                                             d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio                                                                             ns_mode). (rejection id: 1)
(node:1913) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre                                                                             cated. In the future, promise rejections that are not handled will terminate the                                                                              Node.js process with a non-zero exit code.

**Comment by shabunin** [comment]
Hi

What is the board-computer you are working with?

This error is indicating that some process is already working with serialport device.
If you have created and started systemd service, then it should work in background.

**Comment by cougalix** [comment]
raspberry pi 3B with buster lite
i install your 1st bobaos before...
have i some uninstall to do before installing bobaoskit ?

**Comment by shabunin** [comment]
you should stop and disable autostart of bdsd service

If you installed it in user scope

```text
systemctl --user stop bdsd.service
systemctl --user disable bdsd.service
```

anyway, you may examine running processes on your raspberry pi with `htop`

**Comment by cougalix** [comment]
it's a live ;-)
TY

**Comment by shabunin** [comment]
Good luck!
